### ISSUE TITLE
python command on Windows

### ISSUE THREAD

**Issue by anthonyyangdev** [kevinsun-dev/harmonylang#21]
Currently, when getting the user's Python command, we default to `python3`. This does not always work because it is possible for `python` to be a command but not `python3`.

**Comment by kevinsun-dev** [comment]
Yeah, it might install as `python` rather than `python3`, but that's fine. You can set the settings to use a different command.
Preferences > HarmonyLang > Python Compiler Path (set from default null to `python` to solve this problem).

**Comment by anthonyyangdev** [comment]
Let's make this fact more obvious in the documentation at least. At the moment, the warning message doesn't tell you to set the Python path in settings.json
